// <auto-generated />
using System;
using Itransition_Task4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Itransition_Task4.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260419224914_FixDynamicDataInSeed")]
    partial class FixDynamicDataInSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Itransition_Task4.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmationToken")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResetToken")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            HashedPassword = "$2a$11$u1epTMFLWNZ39L6QNgJqDey.8E5vcmHTspZtuKYxNN8dt7k1XVUuu",
                            LastLoginTime = new DateTime(2026, 4, 19, 22, 49, 13, 145, DateTimeKind.Utc).AddTicks(9431),
                            Name = "Admin",
                            RegistrationDate = new DateTime(2026, 4, 19, 22, 49, 12, 848, DateTimeKind.Utc).AddTicks(1131),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "john@example.com",
                            HashedPassword = "$2a$11$bJ0xzWrOxlOglTbVIvKFd.eCJH5VrLvAwfsZ2UIe.byEs021hgWQ.",
                            LastLoginTime = new DateTime(2026, 4, 18, 22, 49, 13, 295, DateTimeKind.Utc).AddTicks(2236),
                            Name = "John Doe",
                            RegistrationDate = new DateTime(2026, 4, 19, 22, 49, 13, 146, DateTimeKind.Utc).AddTicks(1433),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "jane@example.com",
                            HashedPassword = "$2a$11$eYctyqiQnVhP6S3aVXb0xOGaaha/4sYTwiZ2HYHVLoHy5wkXjcF66",
                            LastLoginTime = new DateTime(2026, 4, 19, 17, 49, 13, 443, DateTimeKind.Utc).AddTicks(6606),
                            Name = "Jane Smith",
                            RegistrationDate = new DateTime(2026, 4, 19, 22, 49, 13, 295, DateTimeKind.Utc).AddTicks(2479),
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "ivan@example.com",
                            HashedPassword = "$2a$11$lPsm3NIplxn6pgiqOPSxuuiURX6dYfVYhVB2uSsVp5XwA7J.NHI/q",
                            LastLoginTime = new DateTime(2026, 4, 16, 22, 49, 13, 593, DateTimeKind.Utc).AddTicks(7017),
                            Name = "Ivan Ivanov",
                            RegistrationDate = new DateTime(2026, 4, 19, 22, 49, 13, 443, DateTimeKind.Utc).AddTicks(6849),
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
