// <auto-generated />
using System;
using Itransition_Task4;
using Itransition_Task4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Itransition_Task4.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260414173508_AddedPasswords")]
    partial class AddedPasswords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Itransition_Task4.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Statuses")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            HashedPassword = "a",
                            LastLoginTime = new DateTime(2026, 4, 14, 17, 35, 7, 714, DateTimeKind.Utc).AddTicks(6202),
                            Name = "Admin",
                            Statuses = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "john@example.com",
                            HashedPassword = "b",
                            LastLoginTime = new DateTime(2026, 4, 13, 17, 35, 7, 714, DateTimeKind.Utc).AddTicks(7526),
                            Name = "John Doe",
                            Statuses = 0
                        },
                        new
                        {
                            Id = 3,
                            Email = "jane@example.com",
                            HashedPassword = "c",
                            LastLoginTime = new DateTime(2026, 4, 14, 12, 35, 7, 714, DateTimeKind.Utc).AddTicks(7617),
                            Name = "Jane Smith",
                            Statuses = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "ivan@example.com",
                            HashedPassword = "d",
                            LastLoginTime = new DateTime(2026, 4, 14, 17, 35, 7, 714, DateTimeKind.Utc).AddTicks(7632),
                            Name = "Ivan Ivanov",
                            Statuses = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
